[package]
name = "rust-avltree"
version = "0.1.0"
authors = ["renyanwu <349426266@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
